index.js
package.json
tests/routes.test.js
yarn.lock

* tests for home and showcase page
* small refactor in index.js to export app for tests

Tests for routes

---

routes/index.js
tests/routes.test.js
views/dashboard.html
views/owner.html
views/search.html

Porting old pages from DPR-API:
* `/publisher`
* `/search`
* `/dashboard`

Porting pages

---

README.md
config/index.js
lib/index.js
tests/fixtures/index.js

* setup DATAHUB_API to be either setup from env variable or default value is https://api.datahub.io
* refactored lib/index.js
* refactored tests

setup config var DATAHUB_API

---

views/base.html

- only normalize.js import is unnecessary
- All other imports are required
- All other scripts looked fine

[removed-unnecessary-import][xs]: removed unnecessary import -refs #28

---

docs/data-packages.md
docs/data-packages/csv.md
docs/data-packages/publish-any.md
docs/data-packages/publish-faq.md
docs/data-packages/publish-geo.md
docs/data-packages/publish-online.md
docs/data-packages/publish-tabular.md
docs/data-packages/publish.md
docs/data-packages/tabular.md

* created new directory `data-packages` and added the following pages: `csv.md, tabular.md, publish.md, publish-any.md, publish-faq.md, publish-geo.md, publish-online.md, publish-tabular.md` and updated links appropriately
* created `data-packages.md`

[moved-docs][m]: moved docs with updating links - refs #79

---

docs/core-data/curators-guide.md
views/docs_home.html

* updated core data curators page

[docs][xs] updated link to core data curators guide - refs #100

---

docs/data-packages.md
docs/data-packages/csv.md
docs/data-packages/tabular.md
docs/features/data-cli.md
docs/features/views.md

* minor fixes in markdown syntax

[fixes-markdown][xs]: minor fixes in docs - refs #106

---

views/_instructions.html

Updated instruction for R usage. Since our R library is outdated, I used simple code to get metadata and data itself.

[instructions][xs]: R usage for getting metadata and data - refs #115

---

views/_instructions.html

* Updated R instructions, since it was reported by user https://github.com/datahubio/qa/issues/31

[instructions][xs]: updated R instruction which is somehow did not work

---

README.md
package.json
routes/index.js
tests/routes.test.js
views/awesome.html

What were done in the branch:
* tests for `/awesome` route is added
* `/awesome` route added  => https://github.com/datahubio/awesome/blob/master/index.md)
* `/awesome/something`  => https://github.com/datahubio/awesome/blob/master/something.md
original issue: https://github.com/datahq/pm/issues/77

Awesome page

---

docs/core-data/curators-guide.md

https://github.com/datasets/house-prices-global/issues/1

update curators guide

---

routes/index.js
tests/fixtures/index.js
tests/routes.test.js

* Allow only logged in users to see the shwocase page
* compare to email hash or ownerid (for custom userID)
* Moks and tests updated
fixes #177

[showcase][m]: not allow everyone to see the progress of revision

---

views/pricing.html

* added GA tracking for sign-in and sign-up events

[price-page][xs]: added GA tracking for sign-in and sign-up links

---

views/base.html
views/download.html

1. Changed 'Publish' to 'Download' in a Navbar
2. Changed products order on a 'Download page' (put data-cli above the data-desktop)

[navbar][s] Improve the data-cli findability.

---

routes/index.js
tests/fixtures/index.js
views/search.html

Displaying page number on the search page.
In the image current page is 14

Pagination for search page - refs #195

---

views/_instructions.html

* define repo parameter for install
* Notify to use `sudo`.
fixes #209

[showcase][xs]: update R instruction for Linux machines

---

lib/utils/index.js
routes/index.js
tests/fixtures/index.js
views/owner.html
views/search.html

* added pagination to publishers page

[publisher-page][s]: added pagination to publisher page - refs #218

---

views/showcase.html

The 'data-cli' section is now active by default.

[fix][s] Fix instructions menu bug

---

routes/index.js
views/login.html

Google login enabled. Looks like this

[login][s]: enable google login and track clicks - fixes #241

---

views/docs_home.html

Issue: https://github.com/datahq/datahub-qa/issues/210
Doc: https://github.com/datahq/datahub-content/blob/master/docs/getting-started/datapackage-find-prepare-share-guide.md
I'm not sure about the Title name and description, you are welcome to give any suggestions.

[docs] find-prepare-share datapackage guide

---

views/docs_home.html

Issue: https://github.com/datahq/datahub-qa/issues/181
Page: https://github.com/datahq/datahub-content/blob/master/docs/faq.md

[docs] a FAQ page added

---

views/base.html
views/home.html

* Updated scroll issue on showcase page

Updated scroll issue fix on showcase page

---

Dockerfile
package.json
routes/index.js
yarn.lock

Making puppeteer work on docker containers

Puppeteer experiments

---

views/base.html

* Chat link opening in new tab

[improvement][xs] - updated chat link - #357

---

routes/index.js
views/awesome.html

Remove the edit widget and made the editing optional on the awesome pages

[improvement][sm] - removed editable awesome page - #351

---

views/premium-data.html

manadatory fields and new inputs
minor design updates

Premium data modal improvements

---

views/base.html
views/showcase.html

Jquery errors had affected widgets and small jquery elements

[bugfix][sm] - fixed jquery $ error - #407

---

views/base.html

defering the javascript released some errors on elements directly depending on jquery

[sm][page-seped] - async javascript delivery - #409

---

views/base.html

script async leading to BS JS missing the jquery

updates to scripts in base

---

views/base.html

Added google analytics as a quick fix since google tag manager is not working correctly.

[google analytics][s]: added google analytics as a quick fix
